
export const cantons = [
    { value: 'AG', label: 'Aargau' },
    { value: 'AR', label: 'Appenzell Ausserrhoden' },
    { value: 'AI', label: 'Appenzell Innerrhoden' },
    { value: 'BL', label: 'Basel-Landschaft' },
    { value: 'BS', label: 'Basel-Stadt' },
    { value: 'BE', label: 'Bern' },
    { value: 'FR', label: 'Freiburg' },
    { value: 'GE', label: 'Genf' },
    { value: 'GL', label: 'Glarus' },
    { value: 'GR', label: 'Graubünden' },
    { value: 'JU', label: 'Jura' },
    { value: 'LU', label: 'Luzern' },
    { value: 'NE', label: 'Neuenburg' },
    { value: 'NW', label: 'Nidwalden' },
    { value: 'OW', label: 'Obwalden' },
    { value: 'SH', label: 'Schaffhausen' },
    { value: 'SZ', label: 'Schwyz' },
    { value: 'SO', label: 'Solothurn' },
    { value: 'SG', label: 'St. Gallen' },
    { value: 'TI', label: 'Tessin' },
    { value: 'TG', label: 'Thurgau' },
    { value: 'UR', label: 'Uri' },
    { value: 'VD', label: 'Waadt' },
    { value: 'VS', label: 'Wallis' },
    { value: 'ZG', label: 'Zug' },
    { value: 'ZH', label: 'Zürich' },
];
